### ISSUE TITLE
What should we cut?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/python-second-language#10]
As of 2016-09-13, there's too much in this lesson for one day - what should we cut and why?

**Comment by dopplershift** [comment]
I'd cut:
- profiling
- "getting data from the web".

While I think both are valuable tools in the tool box, I don't consider them core knowledge, broadly applicable to scientific users--especially not when weighed against other subjects that would otherwise need to be cut.

**Comment by mikej888** [comment]
I'd cut NumPy Arrays, Pandas, Plotting. The students can be made aware of these packages but the other content is more fundamental to both learning Python and, through that, good programming practices.

If keeping profiling, move it to after testing (don't want to introduce bugs when tuning).

**Comment by mfoos** [comment]
I'd also add that Pandas has some different terminology that's similar-but-not-identical to base Python (I'm thinking of Series, for instance) and that's a huge stumbling block for me when I'm a learner. And I agree that awareness of those packages is important.
